package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * Assistant generated by hbm2java
 */
public class Assistant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private AssistantId id;
	private Professor reunion;

	public Assistant() {
	}

	public Assistant(AssistantId id, Professor reunion) {
		this.id = id;
		this.reunion = reunion;
	}

	public AssistantId getId() {
		return this.id;
	}

	public void setId(AssistantId id) {
		this.id = id;
	}

	public Professor getReunion() {
		return this.reunion;
	}

	public void setReunion(Professor reunion) {
		this.reunion = reunion;
	}

}
