package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * AssistantId generated by hbm2java
 */
public class AssistantId implements java.io.Serializable {

	private int reunionId;
	private int userId;

	public AssistantId() {
	}

	public AssistantId(int reunionId, int userId) {
		this.reunionId = reunionId;
		this.userId = userId;
	}

	public int getReunionId() {
		return this.reunionId;
	}

	public void setReunionId(int reunionId) {
		this.reunionId = reunionId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AssistantId))
			return false;
		AssistantId castOther = (AssistantId) other;

		return (this.getReunionId() == castOther.getReunionId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getReunionId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
