package com.Reto2.RetoServer.Database.Entity;
// Generated 17 ene 2025, 15:37:13 by Hibernate Tools 6.5.1.Final

import com.google.gson.annotations.Expose;

/**
 * Assistant generated by hbm2java
 */
public class Assistant implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 128616636880581808L;
	private Integer assistantId;
	private Professor professor;
	private Reunion reunion;

	public Assistant() {
	}

	public Assistant(Professor professor, Reunion reunion) {
		this.professor = professor;
		this.reunion = reunion;
	}

	public Integer getAssistantId() {
		return this.assistantId;
	}

	public void setAssistantId(Integer assistantId) {
		this.assistantId = assistantId;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public Reunion getReunion() {
		return this.reunion;
	}

	public void setReunion(Reunion reunion) {
		this.reunion = reunion;
	}

	@Override
	public String toString() {
		return "Assistant [assistantId=" + assistantId + ", professor=" + professor + ", reunion=" + reunion + "]";
	}

}
