package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private CourseId id;
	private Schedule matriculation;
	private Subject subject;
	private String title;
	private String email;
	private String description;

	public Course() {
	}

	public Course(CourseId id, Schedule matriculation, Subject subject) {
		this.id = id;
		this.matriculation = matriculation;
		this.subject = subject;
	}

	public Course(CourseId id, Schedule matriculation, Subject subject, String title, String email,
			String description) {
		this.id = id;
		this.matriculation = matriculation;
		this.subject = subject;
		this.title = title;
		this.email = email;
		this.description = description;
	}

	public CourseId getId() {
		return this.id;
	}

	public void setId(CourseId id) {
		this.id = id;
	}

	public Schedule getMatriculation() {
		return this.matriculation;
	}

	public void setMatriculation(Schedule matriculation) {
		this.matriculation = matriculation;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
