package com.Reto2.RetoServer.Database.Entity;

// default package
// Generated 22 ene 2025 2:12:36 by Hibernate Tools 6.2.5.Final

/**
 * Documents generated by hbm2java
 */
public class Documents implements java.io.Serializable {

	private static final long serialVersionUID = -1814230672591737626L;
	private Integer documentId;
	private Course course;
	private Subject subject;
	private int allowedCourse;
	private String link;

	public Documents() {
	}

	public Documents(Course course, Subject subject, int allowedCourse, String link) {
		this.course = course;
		this.subject = subject;
		this.allowedCourse = allowedCourse;
		this.link = link;
	}

	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public int getAllowedCourse() {
		return this.allowedCourse;
	}

	public void setAllowedCourse(int allowedCourse) {
		this.allowedCourse = allowedCourse;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

}
