package com.Reto2.RetoServer.Database.Entity;
// Generated 27 ene 2025, 16:10:05 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

import com.google.gson.annotations.Expose;

/**
 * Externalcourse generated by hbm2java
 */
public class Externalcourse implements java.io.Serializable {

	private static final long serialVersionUID = -7253835337036750560L;
	@Expose
	private Integer externalCourseId;
	@Expose
	private int telephone;
	@Expose
	private String title;
	@Expose
	private String description;
	@Expose
	private Date startDate;
	@Expose
	private Date endDate;
	@Expose
	private int schedule;
	@Expose
	private float latitude;
	@Expose
	private float longitude;

	public Externalcourse() {
	}

	public Externalcourse(int telephone, String title, String description, Date startDate, Date endDate, int schedule,
			float latitude, float longitude) {
		this.telephone = telephone;
		this.title = title;
		this.description = description;
		this.startDate = startDate;
		this.endDate = endDate;
		this.schedule = schedule;
		this.latitude = latitude;
		this.longitude = longitude;
	}

	public Integer getExternalCourseId() {
		return this.externalCourseId;
	}

	public void setExternalCourseId(Integer externalCourseId) {
		this.externalCourseId = externalCourseId;
	}

	public int getTelephone() {
		return this.telephone;
	}

	public void setTelephone(int telephone) {
		this.telephone = telephone;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public int getSchedule() {
		return this.schedule;
	}

	public void setSchedule(int schedule) {
		this.schedule = schedule;
	}

	public float getLatitude() {
		return this.latitude;
	}

	public void setLatitude(float lattitude) {
		this.latitude = lattitude;
	}

	public float getLongitude() {
		return this.longitude;
	}

	public void setLongitude(float longitude) {
		this.longitude = longitude;
	}

}
