package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * MatriculationId generated by hbm2java
 */
public class MatriculationId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int matriculationId;
	private int userId;

	public MatriculationId() {
	}

	public MatriculationId(int matriculationId, int userId) {
		this.matriculationId = matriculationId;
		this.userId = userId;
	}

	public int getMatriculationId() {
		return this.matriculationId;
	}

	public void setMatriculationId(int matriculationId) {
		this.matriculationId = matriculationId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatriculationId))
			return false;
		MatriculationId castOther = (MatriculationId) other;

		return (this.getMatriculationId() == castOther.getMatriculationId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatriculationId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
