package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Matriculation generated by hbm2java
 */
public class Matriculation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private MatriculationId id;
	private Student student;
	private Date date;
	private Set courses = new HashSet(0);

	public Matriculation() {
	}

	public Matriculation(MatriculationId id, Student student) {
		this.id = id;
		this.student = student;
	}

	public Matriculation(MatriculationId id, Student student, Date date, Set courses) {
		this.id = id;
		this.student = student;
		this.date = date;
		this.courses = courses;
	}

	public MatriculationId getId() {
		return this.id;
	}

	public void setId(MatriculationId id) {
		this.id = id;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
