package com.Reto2.RetoServer.Database.Entity;
// Generated 17 ene 2025, 15:37:13 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Matriculation generated by hbm2java
 */
public class Matriculation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4678374157046571920L;
	private Integer matriculationId;
	private Student student;
	private Course course;
	private Date matriculationDate;

	public Matriculation() {
	}

	public Matriculation(Date matriculationDate) {
		this.matriculationDate = matriculationDate;
	}

	public Matriculation(Student student, Course course, Date matriculationDate) {
		this.student = student;
		this.course = course;
		this.matriculationDate = matriculationDate;
	}

	public Integer getMatriculationId() {
		return this.matriculationId;
	}

	public void setMatriculationId(Integer matriculationId) {
		this.matriculationId = matriculationId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Date getMatriculationDate() {
		return this.matriculationDate;
	}

	public void setMatriculationDate(Date matriculationDate) {
		this.matriculationDate = matriculationDate;
	}

	@Override
	public String toString() {
		return "Matriculation [matriculationId=" + matriculationId + ", student=" + student + ", course=" + course
				+ ", matriculationDate=" + matriculationDate + "]";
	}
	
}
