package com.Reto2.RetoServer.Database.Entity;
// Generated 27 ene 2025, 16:10:05 by Hibernate Tools 6.5.1.Final

import java.sql.Date;

/**
 * Matriculation generated by hbm2java
 */
public class Matriculation implements java.io.Serializable {

	private Integer matriculationId;
	private Student student;
	private Course course;
	private Date matriculationDate;

	public Matriculation() {
	}

	public Matriculation(Date matriculationDate) {
		this.matriculationDate = matriculationDate;
	}

	public Matriculation(Student student, Course course, Date matriculationDate) {
		this.student = student;
		this.course = course;
		this.matriculationDate = matriculationDate;
	}

	public Integer getMatriculationId() {
		return this.matriculationId;
	}

	public void setMatriculationId(Integer matriculationId) {
		this.matriculationId = matriculationId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public Date getMatriculationDate() {
		return this.matriculationDate;
	}

	public void setMatriculationDate(Date matriculationDate) {
		this.matriculationDate = matriculationDate;
	}

}
