package com.Reto2.RetoServer.Database.Entity;
// Generated 17 ene 2025, 15:37:13 by Hibernate Tools 6.5.1.Final

import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;

/**
 * Reunion generated by hbm2java
 */
public class Reunion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8717766209919193552L;
	private Integer reunionId;
	private Professor professor;
	private String title;
	private String affair;
	private Timestamp dayAndHour;
	private String class_;
	private int sendedRequest;
	private String reunionState;
	private Set assistants = new HashSet(0);

	public Reunion() {
	}

	public Reunion(String title, String affair, Timestamp dayAndHour, String class_, int sendedRequest,
			String reunionState) {
		this.title = title;
		this.affair = affair;
		this.dayAndHour = dayAndHour;
		this.class_ = class_;
		this.sendedRequest = sendedRequest;
		this.reunionState = reunionState;
	}

	public Reunion(Professor professor, String title, String affair, Timestamp dayAndHour, String class_,
			int sendedRequest, String reunionState, Set assistants) {
		this.professor = professor;
		this.title = title;
		this.affair = affair;
		this.dayAndHour = dayAndHour;
		this.class_ = class_;
		this.sendedRequest = sendedRequest;
		this.reunionState = reunionState;
		this.assistants = assistants;
	}

	public Integer getReunionId() {
		return this.reunionId;
	}

	public void setReunionId(Integer reunionId) {
		this.reunionId = reunionId;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAffair() {
		return this.affair;
	}

	public void setAffair(String affair) {
		this.affair = affair;
	}

	public Timestamp getDayAndHour() {
		return this.dayAndHour;
	}

	public void setDayAndHour(Timestamp dayAndHour) {
		this.dayAndHour = dayAndHour;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public int getSendedRequest() {
		return this.sendedRequest;
	}

	public void setSendedRequest(int sendedRequest) {
		this.sendedRequest = sendedRequest;
	}

	public String getReunionState() {
		return this.reunionState;
	}

	public void setReunionState(String reunionState) {
		this.reunionState = reunionState;
	}

	public Set getAssistants() {
		return this.assistants;
	}

	public void setAssistants(Set assistants) {
		this.assistants = assistants;
	}

}