package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reunion generated by hbm2java
 */
public class Reunion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer reunionId;
	private Professor professor;
	private String title;
	private String affair;
	private Date dayAndHour;
	private String class_;
	private Integer sendedRequest;
	private String status;
	private String requestedProfessorName;
	private Set assistants = new HashSet(0);

	public Reunion() {
	}

	public Reunion(Professor professor, String title, String affair, Date dayAndHour, String class_,
			Integer sendedRequest, String status, String requestedProfessorName, Set assistants) {
		this.professor = professor;
		this.title = title;
		this.affair = affair;
		this.dayAndHour = dayAndHour;
		this.class_ = class_;
		this.sendedRequest = sendedRequest;
		this.status = status;
		this.requestedProfessorName = requestedProfessorName;
		this.assistants = assistants;
	}

	public Integer getReunionId() {
		return this.reunionId;
	}

	public void setReunionId(Integer reunionId) {
		this.reunionId = reunionId;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAffair() {
		return this.affair;
	}

	public void setAffair(String affair) {
		this.affair = affair;
	}

	public Date getDayAndHour() {
		return this.dayAndHour;
	}

	public void setDayAndHour(Date dayAndHour) {
		this.dayAndHour = dayAndHour;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public Integer getSendedRequest() {
		return this.sendedRequest;
	}

	public void setSendedRequest(Integer sendedRequest) {
		this.sendedRequest = sendedRequest;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRequestedProfessorName() {
		return this.requestedProfessorName;
	}

	public void setRequestedProfessorName(String requestedProfessorName) {
		this.requestedProfessorName = requestedProfessorName;
	}

	public Set getAssistants() {
		return this.assistants;
	}

	public void setAssistants(Set assistants) {
		this.assistants = assistants;
	}

}
