package com.Reto2.RetoServer.Database.Entity;
// Generated 29 ene 2025 15:24:49 by Hibernate Tools 6.2.5.Final

import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Reunion generated by hbm2java
 */
public class Reunion implements java.io.Serializable {

	private static final long serialVersionUID = -302842241366381047L;
	@Expose
	private Integer reunionId;
	private Professor professor;
	@Expose
	private String title;
	@Expose
	private String affair;
	@Expose
	private Date day;
	@Expose
	private String class_;
	@Expose
	private int reunionState;
	@Expose
	private int hour;
	private Set<Assistant> assistants = new HashSet<Assistant>(0);

	public Reunion() {
	}

	public Reunion(Professor professor, String title, String affair, Date day, String class_, int reunionState,
			int hour, Set<Assistant> assistants) {
		this.professor = professor;
		this.title = title;
		this.affair = affair;
		this.day = day;
		this.class_ = class_;
		this.reunionState = reunionState;
		this.hour = hour;
		this.assistants = assistants;
	}

	public Integer getReunionId() {
		return this.reunionId;
	}

	public void setReunionId(Integer reunionId) {
		this.reunionId = reunionId;
	}

	public Professor getProfessor() {
		return this.professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getAffair() {
		return this.affair;
	}

	public void setAffair(String affair) {
		this.affair = affair;
	}

	public Date getDay() {
		return this.day;
	}

	public void setDay(Date day) {
		this.day = day;
	}

	public String getClass_() {
		return this.class_;
	}

	public void setClass_(String class_) {
		this.class_ = class_;
	}

	public int getReunionState() {
		return this.reunionState;
	}

	public void setReunionState(int reunionState) {
		this.reunionState = reunionState;
	}

	public int getHour() {
		return this.hour;
	}

	public void setHour(int hour) {
		this.hour = hour;
	}

	public Set<Assistant> getAssistants() {
		return this.assistants;
	}

	public void setAssistants(Set<Assistant> assistants) {
		this.assistants = assistants;
	}

}
