package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * ScheduleId generated by hbm2java
 */
public class ScheduleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int scheduleId;
	private int userId;

	public ScheduleId() {
	}

	public ScheduleId(int scheduleId, int userId) {
		this.scheduleId = scheduleId;
		this.userId = userId;
	}

	public int getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(int scheduleId) {
		this.scheduleId = scheduleId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ScheduleId))
			return false;
		ScheduleId castOther = (ScheduleId) other;

		return (this.getScheduleId() == castOther.getScheduleId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getScheduleId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
