package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ScheduleId id;
	private Integer day;
	private Integer week;
	private String tipoDato;
	private Set courses = new HashSet(0);

	public Schedule() {
	}

	public Schedule(ScheduleId id) {
		this.id = id;
	}

	public Schedule(ScheduleId id, Integer day, Integer week, String tipoDato, Set courses) {
		this.id = id;
		this.day = day;
		this.week = week;
		this.tipoDato = tipoDato;
		this.courses = courses;
	}

	public ScheduleId getId() {
		return this.id;
	}

	public void setId(ScheduleId id) {
		this.id = id;
	}

	public Integer getDay() {
		return this.day;
	}

	public void setDay(Integer day) {
		this.day = day;
	}

	public Integer getWeek() {
		return this.week;
	}

	public void setWeek(Integer week) {
		this.week = week;
	}

	public String getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(String tipoDato) {
		this.tipoDato = tipoDato;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
