package com.Reto2.RetoServer.Database.Entity;
// Generated 17 ene 2025, 15:37:13 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8817143435324917310L;
	private Integer scheduleId;
	private Client client;
	private int scheduleDay;
	private int scheduleWeek;
	private String tipoDato;
	private Set courses = new HashSet(0);

	public Schedule() {
	}

	public Schedule(int scheduleDay, int scheduleWeek, String tipoDato) {
		this.scheduleDay = scheduleDay;
		this.scheduleWeek = scheduleWeek;
		this.tipoDato = tipoDato;
	}

	public Schedule(Client client, int scheduleDay, int scheduleWeek, String tipoDato, Set courses) {
		this.client = client;
		this.scheduleDay = scheduleDay;
		this.scheduleWeek = scheduleWeek;
		this.tipoDato = tipoDato;
		this.courses = courses;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public int getScheduleDay() {
		return this.scheduleDay;
	}

	public void setScheduleDay(int scheduleDay) {
		this.scheduleDay = scheduleDay;
	}

	public int getScheduleWeek() {
		return this.scheduleWeek;
	}

	public void setScheduleWeek(int scheduleWeek) {
		this.scheduleWeek = scheduleWeek;
	}

	public String getTipoDato() {
		return this.tipoDato;
	}

	public void setTipoDato(String tipoDato) {
		this.tipoDato = tipoDato;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
