package com.Reto2.RetoServer.Database.Entity;
// Generated 31 ene 2025, 20:13:23 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Schedule generated by hbm2java
 */
public class Schedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6560388603190067848L;
	@Expose
	private Integer scheduleId;
	@Expose
	private Subject subject;
	private Client client;
	@Expose
	private int scheduleDay;
	@Expose
	private Integer scheduleHour;
	private Set courses = new HashSet(0);

	public Schedule() {
	}

	public Schedule(int scheduleDay) {
		this.scheduleDay = scheduleDay;
	}

	public Schedule(Subject subject, Client client, int scheduleDay, Integer scheduleHour, Set courses) {
		this.subject = subject;
		this.client = client;
		this.scheduleDay = scheduleDay;
		this.scheduleHour = scheduleHour;
		this.courses = courses;
	}

	public Integer getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Integer scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Subject getSubject() {
		return this.subject;
	}

	public void setSubject(Subject subject) {
		this.subject = subject;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public int getScheduleDay() {
		return this.scheduleDay;
	}

	public void setScheduleDay(int scheduleDay) {
		this.scheduleDay = scheduleDay;
	}

	public Integer getScheduleHour() {
		return this.scheduleHour;
	}

	public void setScheduleHour(Integer scheduleHour) {
		this.scheduleHour = scheduleHour;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}
	
}
