package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private StudentId id;
	private Client client;
	private Character year;
	private Boolean intensiveDual;
	private Set matriculation = new HashSet(0);

	public Student() {
	}

	public Student(StudentId id, Client client) {
		this.id = id;
		this.client = client;
	}

	public Student(StudentId id, Client client, Character year, Boolean intensiveDual, Set matriculations) {
		this.id = id;
		this.client = client;
		this.year = year;
		this.intensiveDual = intensiveDual;
		this.matriculation = matriculations;
	}

	public StudentId getId() {
		return this.id;
	}

	public void setId(StudentId id) {
		this.id = id;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public Character getYear() {
		return this.year;
	}

	public void setYear(Character year) {
		this.year = year;
	}

	public Boolean getIntensiveDual() {
		return this.intensiveDual;
	}

	public void setIntensiveDual(Boolean intensiveDual) {
		this.intensiveDual = intensiveDual;
	}

	public Set getMatriculations() {
		return this.matriculation;
	}

	public void setMatriculations(Set matriculation) {
		this.matriculation = matriculation;
	}

}
