package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private SubjectId id;
	private String subjectName;
	private Set courses = new HashSet(0);

	public Subject() {
	}

	public Subject(SubjectId id) {
		this.id = id;
	}

	public Subject(SubjectId id, String subjectName, Set courses) {
		this.id = id;
		this.subjectName = subjectName;
		this.courses = courses;
	}

	public SubjectId getId() {
		return this.id;
	}

	public void setId(SubjectId id) {
		this.id = id;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Set getCourses() {
		return this.courses;
	}

	public void setCourses(Set courses) {
		this.courses = courses;
	}

}
