package com.Reto2.RetoServer.Database.Entity;
// Generated 27 ene 2025, 16:10:05 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	private Integer subjectId;
	private Course course;
	private String subjectName;
	private Set documentses = new HashSet(0);

	public Subject() {
	}

	public Subject(Course course, String subjectName) {
		this.course = course;
		this.subjectName = subjectName;
	}

	public Subject(Course course, String subjectName, Set documentses) {
		this.course = course;
		this.subjectName = subjectName;
		this.documentses = documentses;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

	public Set getDocumentses() {
		return this.documentses;
	}

	public void setDocumentses(Set documentses) {
		this.documentses = documentses;
	}

}
