package com.Reto2.RetoServer.Database.Entity;
// Generated 17 ene 2025, 15:37:13 by Hibernate Tools 6.5.1.Final

/**
 * Subject generated by hbm2java
 */
public class Subject implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4325507360240570203L;
	private Integer subjectId;
	private Course course;
	private String subjectName;

	public Subject() {
	}

	public Subject(Course course, String subjectName) {
		this.course = course;
		this.subjectName = subjectName;
	}

	public Integer getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(Integer subjectId) {
		this.subjectId = subjectId;
	}

	public Course getCourse() {
		return this.course;
	}

	public void setCourse(Course course) {
		this.course = course;
	}

	public String getSubjectName() {
		return this.subjectName;
	}

	public void setSubjectName(String subjectName) {
		this.subjectName = subjectName;
	}

}
