package com.Reto2.RetoServer.Database.Entity;
// Generated 16 ene 2025, 17:35:05 by Hibernate Tools 6.5.1.Final

/**
 * SubjectId generated by hbm2java
 */
public class SubjectId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int courseId;
	private int subjectId;
	private int userId;

	public SubjectId() {
	}

	public SubjectId(int courseId, int subjectId, int userId) {
		this.courseId = courseId;
		this.subjectId = subjectId;
		this.userId = userId;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public int getSubjectId() {
		return this.subjectId;
	}

	public void setSubjectId(int subjectId) {
		this.subjectId = subjectId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SubjectId))
			return false;
		SubjectId castOther = (SubjectId) other;

		return (this.getCourseId() == castOther.getCourseId()) && (this.getSubjectId() == castOther.getSubjectId())
				&& (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCourseId();
		result = 37 * result + this.getSubjectId();
		result = 37 * result + this.getUserId();
		return result;
	}

}
